"use client";

import { useState } from "react";

export function CatchMeUpButton({ roomId }: { roomId: string }) {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function fetchSummary() {
    setLoading(true);
    setError(null);
    setSummary(null);
    try {
      const res = await fetch("/api/ai/summarize", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ roomId })
      });
      if (res.status === 503) {
        setError("AI features aren't configured on this site yet.");
        return;
      }
      if (!res.ok) {
        const j = await res.json().catch(() => ({}));
        setError(j?.error ?? `failed (${res.status})`);
        return;
      }
      const j = await res.json();
      setSummary(j.summary ?? "");
    } catch (e: any) {
      setError(e?.message ?? "request failed");
    } finally {
      setLoading(false);
    }
  }

  function openModal() {
    setOpen(true);
    void fetchSummary();
  }

  return (
    <>
      <button
        type="button"
        onClick={openModal}
        title="Catch me up — quick summary of recent messages"
        aria-label="Catch me up"
        className="flex shrink-0 items-center gap-1 rounded-lg border border-neon-purple/30 bg-neon-purple/10 px-2.5 py-1.5 text-[11px] text-neon-purple transition hover:bg-neon-purple/20"
      >
        <span aria-hidden>✨</span>
        <span className="hidden md:inline">Catch me up</span>
      </button>

      {open && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm"
          onClick={() => setOpen(false)}
        >
          <div
            className="surface-glass mx-4 w-full max-w-md p-5 shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="mb-3 flex items-center justify-between gap-2">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setOpen(false)}
                  aria-label="Back"
                  title="Back"
                  className="rounded-md border border-white/10 bg-white/5 px-2 py-0.5 text-xs text-white/60 hover:bg-white/10"
                >
                  ←
                </button>
                <h2 className="font-display text-lg font-semibold">
                  <span className="bg-gradient-to-r from-neon-blue to-neon-purple bg-clip-text text-transparent">
                    ✨ Recap
                  </span>
                </h2>
              </div>
              <button
                onClick={() => setOpen(false)}
                aria-label="Close"
                title="Close"
                className="rounded-md border border-white/10 px-2 py-0.5 text-xs text-white/70 hover:bg-white/10"
              >
                ✕
              </button>
            </div>

            {loading && (
              <div className="space-y-2">
                <div className="h-3 w-3/4 animate-pulseDot rounded bg-white/10" />
                <div className="h-3 w-2/3 animate-pulseDot rounded bg-white/10" />
                <div className="h-3 w-1/2 animate-pulseDot rounded bg-white/10" />
              </div>
            )}

            {error && (
              <p className="text-sm text-neon-red">{error}</p>
            )}

            {summary && (
              <div className="whitespace-pre-wrap text-sm leading-relaxed text-white/85">
                {summary}
              </div>
            )}

            <div className="mt-4 flex justify-end gap-2 text-xs">
              <button
                onClick={fetchSummary}
                disabled={loading}
                className="rounded border border-white/10 bg-white/5 px-2 py-1 text-white/70 hover:bg-white/10 disabled:opacity-50"
              >
                ↻ Refresh
              </button>
            </div>
            <p className="mt-3 text-[10px] text-white/30">
              Generated by AI from the last ~80 messages. Treat as a hint, not gospel.
            </p>
          </div>
        </div>
      )}
    </>
  );
}
